[project]
name = "google-search"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.12.3",
    "playwright>=1.55.0",
    "beautifulsoup4>=4.13.5",
    "typer>=0.19.2",
]

[project.scripts]
google-search-server = "google_search_server.main:mcp.run"
google-search-cli = "google_search_server.cli:app"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pyright]
reportCallInDefaultInitializer = false
